#!/bin/bash

set -euo pipefail

ENVIRONMENT="${ENV:-preprod}"
DB_HOST=$(kubectl get secret ppud-replica-database -n "ppud-replacement-${ENVIRONMENT}" -o json | jq -r '.data.host | @base64d')
DB_USER=$(kubectl get secret ppud-replica-database -n "ppud-replacement-${ENVIRONMENT}" -o json | jq -r '.data.username | @base64d')
DB_PASS=$(kubectl get secret ppud-replica-database -n "ppud-replacement-${ENVIRONMENT}" -o json | jq -r '.data.password | @base64d')
PFP_NAME="port-forward-pod-$(whoami)"

echo "Connecting to ${ENVIRONMENT}"

set +e
PFP_COUNT=$(kubectl get pods | grep -c "${PFP_NAME}")
set -e

if [ "${PFP_COUNT}" -eq "0" ]; then
  echo "Starting up port forward pod..."

  kubectl -n "ppud-replacement-${ENVIRONMENT}" run \
    "${PFP_NAME}" \
    --image=ministryofjustice/port-forward \
    --port=1433 \
    --env="REMOTE_HOST=${DB_HOST}" \
    --env="LOCAL_PORT=1433" \
    --env="REMOTE_PORT=1433"

  sleep 5
fi

echo "You can now connect to the database on 127.0.0.1:1433 - username: ${DB_USER} - password: ${DB_PASS}"

kubectl port-forward "${PFP_NAME}" 1433:1433
