---
# Per environment values which override defaults in legacy-ppud-api/values.yaml

environment: dev

generic-service:
  replicaCount: 2

  ingress:
    host: legacy-ppud-api-dev.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.dev.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts

generic-prometheus-alerts:
  alertSeverity: ppud-replacement-alerts
  extraDashboardTags:
    - ppud-replacement
    - dev
