---
# Per environment values which override defaults in legacy-ppud-api/values.yaml

generic-service:
  replicaCount: 4

  ingress:
    host: legacy-ppud-api.hmpps.service.justice.gov.uk

  env:
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.prod.json

# CloudPlatform AlertManager receiver to route promethues alerts to slack
# See https://user-guide.cloud-platform.service.justice.gov.uk/documentation/monitoring-an-app/how-to-create-alarms.html#creating-your-own-custom-alerts

generic-prometheus-alerts:
  alertSeverity: &alertSeverity ppud-replacement-prod
  extraDashboardTags:
    - ppud-replacement
    - &environment prod

# Values needed for templates within this project
environment: *environment
alertSeverity: *alertSeverity
