---
generic-service:
  nameOverride: legacy-ppud-api

  replicaCount: 4

  image:
    repository: quay.io/hmpps/legacy-ppud-api
    tag: app_version    # override at deployment time
    port: 8080

  ingress:
    enabled: false

  livenessProbe:
    httpGet:
      path: /health/liveness
      port: metrics
  readinessProbe:
    httpGet:
      path: /health/readiness
      port: metrics

  # Environment variables to load into the deployment
  env:
    JAVA_OPTS: "-Xmx512m"
    SERVER_PORT: "8080"
    SPRING_PROFILES_ACTIVE: "logstash"
    APPLICATIONINSIGHTS_CONNECTION_STRING: "InstrumentationKey=$(APPINSIGHTS_INSTRUMENTATIONKEY)"
    APPLICATIONINSIGHTS_CONFIGURATION_FILE: applicationinsights.json

  # Pre-existing kubernetes secrets to load as environment variables in the deployment.
  # namespace_secrets:
  #   [name of kubernetes secret]:
  #     [name of environment variable as seen by app]: [key of kubernetes secret to load]

  namespace_secrets:
    legacy-ppud-api:
      APPINSIGHTS_INSTRUMENTATIONKEY: "APPINSIGHTS_INSTRUMENTATIONKEY"

  allowlist:
    office: "217.33.148.210/32"
    health-kick: "35.177.252.195/32"
    mojvpn: "81.134.202.29/32"
    cloudplatform-live1-1: "35.178.209.113/32"
    cloudplatform-live1-2: "3.8.51.207/32"
    cloudplatform-live1-3: "35.177.252.54/32"

  custommetrics:
    enabled: true
    scrapeInterval: 15s
    metricsPath: /prometheus
    metricsPort: 8081

generic-prometheus-alerts:
  targetApplication: &alertTargetApplication legacy-ppud-api

# Values needed for templates within this project
alertTargetApplication: *alertTargetApplication
